training:
  output_dir: "./checkpoints"
  # Dùng đường dẫn ảo để code không lỗi, thực tế load từ HuggingFace
  train_img_dir: ""
  train_ann: ""
  val_img_dir: ""
  val_ann: ""

  batch_size: 2                  # 2 hoặc 4 tùy VRAM
  epochs: 20
  lr: 2.0e-5                     # LR thấp cho Transformer
  weight_decay: 1.0e-4
  clip_max_norm: 0.1             # Chống bùng nổ gradient
  gradient_accumulation_steps: 4 # Tích lũy để giả lập batch size lớn

model:
  base_model: "SenseTime/deformable-detr"
  num_classes: 46                # CHỐT TỪ EDA
  num_attributes: 294

system:
  device: "cuda"
  num_workers: 2